import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    width: 369,
    height: 120,
    backgroundColor: '#FFFFFFFF',
  },
  Header: {},
  text: {
    fontSize: 32,
    lineHeight: 48,
    fontFamily: 'Lato',
    fontWeight: '700',
    color: '#212121',
    width: 315,
    height: 48,
    marginTop: 14,
    marginLeft: 16,
  },
  text2: {
    fontSize: 16,
    width: 326,
    height: 24,
    lineHeight: 24,
    fontFamily: 'Lato',
    fontWeight: '400',
    color: '#212121',
    letterSpacing: 0.08,
    marginLeft: 16,
  },
  TripAru: {
    color: '#0572E7',
    fontSize: 16,
    marginLeft: 16,
  },

  EmailButton: {
    backgroundColor: '#EE730E',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 83,
    marginLeft: 16,
    borderRadius: 8,
    paddingStart: 16,
    paddingTop: 8,
    paddingEnd: 16,
    paddingBottom: 8,
  },
  EmailLabel: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  iconEmailStyle: {
    width: 30,
    height: 30,
    padding: 1,
  },
  PhoneButton: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    marginLeft: 16,
    borderRadius: 8,
    paddingStart: 16,
    paddingTop: 8,
    paddingEnd: 16,
    paddingBottom: 8,
    borderWidth: 1,
    borderColor: '#b0b0b0',
  },
  PhoneLabel: {
    color: '#212121',
    fontSize: 16,
    fontWeight: '600',
  },
  iconPhoneStyle: {
    width: 30,
    height: 30,
    padding: 1,
  },
  fbButton: {
    backgroundColor: '#0572E7',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    marginLeft: 16,
    borderRadius: 8,
    paddingStart: 16,
    paddingTop: 8,
    paddingEnd: 16,
    paddingBottom: 8,
    borderWidth: 1,
    borderColor: '#b0b0b0',
  },
  fbLabel: {
    color: '#FFFFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  iconfbStyle: {
    width: 30,
    height: 30,
    padding: 1,
  },
  ggButton: {
    backgroundColor: '#C9C9C9',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    marginLeft: 16,
    borderRadius: 8,
    paddingStart: 16,
    paddingTop: 8,
    paddingEnd: 16,
    paddingBottom: 8,
    borderWidth: 1,
    borderColor: '#b0b0b0',
  },
  ggLabel: {
    color: '#212121',
    fontSize: 16,
    fontWeight: '600',
  },
  iconggeStyle: {
    width: 30,
    height: 30,
    padding: 1,
  },
  mota: {
    // fontFamily = FontFamily(Font(R.font.lato)),
    marginLeft: 16,
    marginTop: 255,
    width: 348,
    height: 26,
    fontSize: 11,
    fontWeight: '400',
    color: '#C9C9C9',
    letterSpacing: 0.11,
  },
});
