import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  favoriteIcon: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 25,
    padding: 5,
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  texty: {
    marginTop: 23,
    fontSize: 36,
    fontWeight: '700',
    color: '#212121',
    lineHeight: 48,
    marginStart: 16,
  },
  container: {
    flex: 1,
    backgroundColor: '#F7F7F7',
  },
  textt: {
    marginTop: 33,
    color: '#212121',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  itemContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    marginHorizontal: 10,
    marginVertical: 5,
    padding: 10,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  image: {
    width: 150,
    height: 110,
    borderRadius: 10,
  },
  name: {
    marginTop: 7,
    marginLeft: 10,
    fontSize: 16,
    fontWeight: '700',
    color: '#212121',
  },
  day: {
    marginTop: 8,
    marginLeft: 10,
    fontSize: 14,
    fontWeight: '500',
    color: '#8A8A8A',
  },
  price: {
    marginTop: 8,
    marginLeft: 10,
    fontSize: 16,
    fontWeight: '600',
    color: '#f03939',
  },
  centeredContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
